### ISSUE TITLE
Handling Unhandled Exceptions For Better Log Output

### ISSUE THREAD

**Issue by opgbaudouin** [zengenti/contensis-react-base#5]
Hiya

Since we moved onto CRB 3 (3.0.1-beta.5)  we are seeing a lot more 503 errors being spewed out. 

This is naturally when the server dies (for whatever and whomever) coding issue.

The problem is that when it dies it tends to list the full output of server.js BEFORE it outputs the error which can then be rectified.

I've spotted 2 issues:

1. The Start function does not handle unhandled exceptions - i.e. it just dies. 

Can i suggest this is added:

(taken from https://blog.heroku.com/best-practices-nodejs-errors) 

node_modules/@zengenti/contensis-react-base/cjs/contensis-react-base.js

```
...
function terminate (server, options = { coredump: false, timeout: 500 }) {
  // Exit function
  const exit = code => {
    options.coredump ? process.abort() : process.exit(code)
  }

  return (code, reason) => (err, promise) => {
    if (err && err instanceof Error) {
      // Log error information, use a proper logging library here :)
      console.log('term', err.message, err.stack)
    }

    // Attempt a graceful shutdown
    server.close(exit)
    setTimeout(exit, options.timeout).unref()
  }
}

...
const app = express__default["default"]();

const start = (ReactApp, config, ServerFeatures) => {
....

 app.on('stop', () => {
      server.close(function () {
        console.info('GoodBye :(');
      });
    });
    const exitHandler = terminate(server, {
      coredump: false,
      timeout: 500
    })
    process.on('uncaughtException', exitHandler(1, 'Unexpected Error'))
    process.on('unhandledRejection', exitHandler(1, 'Unhandled Promise'))
    process.on('SIGTERM', exitHandler(0, 'SIGTERM'))
    process.on('SIGINT', exitHandler(0, 'SIGINT'))


...
```

This means that ANY error during express will be handles and the SIGTERM are also a normal way to handle node exits on Linux so a nice extra.

Note AFAIK there is only 1 place where nothing in 'caught' :

4372 on CJD: server$1.renderToString(jsx); -> if something happens it dies yet just above it is a nice try/catch - there is likely a reason for that though.

**Comment by nflatley-zengenti** [comment]
Hi @opgbaudouin 
Thank you for submitting the issue and providing a suggested fix - it has played heavily into the decision making and approach we have taken to finally implement a fix for this problem introduced in Node.js versions 15+

There will be a default process exception handler in place from v3.0.1 onward or available now on npm if installed with the @prerelease tag

https://github.com/zengenti/contensis-react-base/commit/677cd00a474eda9180a084fa1ea4db08b6f0ca12

We have decided to continue with the existing behaviour prior to upgrades to Node.js 16+ as this will work for the majority of our users.

If you wish to handle this yourself (inside your `server.ts` app entrypoint), and/or customise the behaviour (such as executing a graceful shutdown or posting an alert) you can add additional listeners to listen for these exceptions in your app and act accordingly.

If you wish to turn off our exception handling messages and handle it yourself - or simply revert to the default Node.js behaviour we have provided a new option `handleExceptions` in the `ServerConfig` argument of the `server.start()` method.

Hopefully the approach we have taken will cover all the necessary use cases whilst favouring robustness of the web app by default. If finer grained control is required in future we have potential to further develop this solution to provide that 

Please feel free to reach out if you wish to check anything and I would recommend you make a plan to remove the patch from production and replace the `exitHander` (if you still require it) to be inside your web app. In this commit I have also exported the `http.Server` instance, so you could call `ZengentiAppServer.server.close()` method from here - if required.

Thanks again!
Neil
